name: flutter_bloc_network
description: This package helps to manage network states used with flutter_bloc
version: 1.0.6
homepage: https://github.com/Ownii/flutter_bloc_network

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.0.0
  bloc: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
